#!/bin/bash -ue

dotdir=$(dirname "$(realpath "$0")")

####################################
# Basic Installation
####################################

# sudo yum -y update
# sudo yum -y install git
# sudo yum -y install tar

# sudo dnf makecache --refresh
# sudo dnf -y install epel-release
# sudo dnf -y install neovim
# sudo dnf -y install tmux

####################################
# .bash_it
####################################

# git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
# ~/.bash_it/install.sh

### Install packages for completion
# sudo yum install bash-completion
# bash-it enable completion cargo django docker docker-compose git go pip tmux ssh yarn

####################################
# nvm
####################################

# git clone https://github.com/nvm-sh/nvm.git ~/.nvm
# bash-it enable plugin nvm
# source ~/.bashrc
# nvm install --lts

####################################
# golang
####################################
# sudo dnf -y install golang
# bash-it enalbe plugin go

####################################
# Rust
####################################
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# bash-it enable plugin cargo

####################################
# yarn
####################################

# npm i -g yarn

####################################
# lazygit
####################################

# go install github.com/jesseduffield/lazygit@latest

####################################
# lazydocker
####################################

# go install github.com/jesseduffield/lazydocker@latest

####################################
# Docker
####################################

# sudo yum install -y yum-utils device-mapper-persistent-data lvm2
# sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
# sudo yum -y install docker-ce

###  Docker without sudo ###

# sudo groupadd docker
# sudo usermod -aG docker $USER


####################################
# setup neovim
####################################

# if [ -d "$dotdir" ]; then
# 	ln -sf "$dotdir/nvim" "$HOME/.config/nvim"
# fi


####################################
# setup tmux
####################################

# ln -sf "$dotdir/.tmux.conf" "$HOME/.tmux.conf"


####################################
# setup bashrc
####################################

# mkdir -p "$HOME/.bashrc.d"
# ln -sf "$dotdir/bash_env" "$HOME/.bashrc.d/bash_env"


####################################
# setup git
####################################

# git config --global user.email "ppdx999@gmail.com"
# git config --global user.name "ppdx999"
# git config --global core.editor "vim"
# git config --global diff.tool vimdiff
# git config --global difftool.prompt false
